### ISSUE TITLE
Invalid changelog has been validated as valid

### ISSUE THREAD

**Issue by Antondomashnev** [dblock/danger-changelog#16]
Hi @dblock thanks a lot for your gem, using it a lot 👍 

Has just merged a new PR, with apparently changelog issue, but the danger skipped it.
```markdown
## master

## 1.0.1

* Your contribution here.
# [#16](https://github.com/Antondomashnev/jigit/pull/16): Small fixes in set up - [@antondomashnev](https://github.com/antondomashnev).
```

This line `# [#16](https://github.com/Antondomashnev/jigit/pull/16): Small fixes in set up - [@antondomashnev](https://github.com/antondomashnev).` has to have `*` in the beginning as a list entry in markdown.

I'd try to prepare a fix soon, however would love to create an issue first 😄

**Comment by dblock** [comment]
Ah yes, this is a problem. Right now the code skips anything with a `#` because there's no way to distinguish something like `## master` with a changelog line. Not sure whether there's an elegant way to fix it ...

**Comment by dblock** [comment]
Btw, https://github.com/dblock/danger-changelog/issues/7 points to a much more "robust" changelog format in which these things are clear.

**Comment by Antondomashnev** [comment]
Yes, #7 looks interesting, but what it misses - the link to PR and the author of PR, which I personally like. 

Correct me if I'm wrong, but we can skip `##` instead of `#`, so the `## master` will be validated, but the bug above will be failed.

**Comment by dblock** [comment]
I don't think so I've definitely seen CHANGELOGs that use a single `#` for sections.

**Comment by dblock** [comment]
Closed via https://github.com/dblock/danger-changelog/pull/17.
