### ISSUE TITLE
Question: Where to configure the plugin?

### ISSUE THREAD

**Issue by Blackjacx** [dblock/danger-changelog#27]
Hi there and sorry for opening an issue for that! I am new to ruby... Thats why I have the following question:

In which file do I need to write:

    Danger::Changelog.configure do |config|
      config.placeholder_line = "Nothing yet."
    end

**Comment by dblock** [comment]
I believe you can just put this in your Dangerfile, since that is just Ruby. Try that? Maybe help contribute to the documentation?

**Comment by Blackjacx** [comment]
I already tried that and actually it didn't help but gave me an error

**Comment by dblock** [comment]
Care to post the error?

**Comment by dblock** [comment]
Bump @Blackjacx, this worked for me, just tested in #31. I'll close this.
