### ISSUE TITLE
Let users remove the line `* Your contribution here.`

### ISSUE THREAD

**Issue by Blackjacx** [dblock/danger-changelog#29]
Hey there,

in our case this line makes more hassle than it helps. So why you cannot implement it that way that it is removed when I explicitly set:

```
Danger::Changelog.configure do |config|
  config.placeholder_line = ""
end
```

In your code you re-add the line when it is specified to be empty...

**Comment by dblock** [comment]
I would take a PR that allows you not to check for the placeholder line. Maybe it should be set to `nil` here instead of `""`, too.

**Comment by Blackjacx** [comment]
Okidoki, when I have time I will try to give you a PR :-)

Mit freundlichen Grüßen

Stefan Herold

Mobile Software Engineer a.d. 2009

E-Mail stefan.herold@gmail.com

Web www.stefan-herold.net

**Comment by dblock** [comment]
Implemented in https://github.com/dblock/danger-changelog/pull/31.
