### ISSUE TITLE
Support custom CHANGELOG formats.

### ISSUE THREAD

**Issue by dblock** [dblock/danger-changelog#3]
The CocoaPods Dangerfile uses a different format, for example.

https://github.com/CocoaPods/CocoaPods/blob/master/Dangerfile

```
# Request a CHANGELOG entry, and give an example
has_app_changes = !git.modified_files.grep(/lib/).empty?
if !git.modified_files.include?('CHANGELOG.md') && has_app_changes
  fail("Please include a CHANGELOG entry to credit yourself! \nYou can find it at [CHANGELOG.md](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md).", :sticky => false)
  markdown <<-MARKDOWN
Here's an example of your CHANGELOG entry:

'''markdown
* #{pr_title}#{' '}
  [#{pr_author}](https://github.com/#{pr_author})
  [#issue_number](https://github.com/CocoaPods/CocoaPods/issues/issue_number)
'''

*note*: There are two invisible spaces after the entry's text.
MARKDOWN
end
```

It would be nice if these were not a regex, like `[pr]: description - [@author](url)`.

**Comment by AliSoftware** [comment]
I'd love to see that and help, as I use a similar format

```markdown
* Blah blah, describe your change here, and wrap it to 80
  characters please, with full-stop and 2 spaces at the end.  
  [YourName](https://github.com/yourhandle)
  [#42](https://github.com/SwiftGen/SwiftGen/pulls/42)
```

I'm not sure a regex would cover enough indeed (e.g. check that the `.  ` is on the last line, in case the description text spans on more than one line and is not on the same line as the `*`, etc)

Also, lonely links `[xx](yy)` which are not just below a bullet-point should generate a warning too (= make sure links are right below the line describing the change especially the one ending with `.  `), but there can be multiple links listed for that entry (the author's GitHub, the PR url, any related issue url that can also be relevant…)… so making that "custom format pattern" should also support "repeating" features like the `*` does for regex I guess

**Comment by dblock** [comment]
I think that beyond regex, we need to enable a lambda that checks the format. PRs welcome!

**Comment by dblock** [comment]
Closing via #44
