### ISSUE TITLE
Danger comment with a trailing space is not actionable

### ISSUE THREAD

**Issue by Blackjacx** [dblock/danger-changelog#52]
When danger reports a wrong changelog format this comment does not automatically disappear when the changelog has been fixed.

Is there maybe a setting I am missing?

**Comment by dblock** [comment]
It does disappear. I bet you the fix is incorrect, often a trailing space that doesn't show well?

**Comment by Blackjacx** [comment]
Ahh kk good to know! Feel free to close 👍

**Comment by dblock** [comment]
Was that it @Blackjacx ? I think the plugin should do a better job saying so, it's impossible to see in the comment. I'll leave this to fix.

**Comment by Blackjacx** [comment]
Hm nah, so we fixed the issue and then left the changelog the comment was still there, unresolved. In new PRs the warning does not appear which means the changelog is `really` fixed and the comment is somehow sticky.
