### ISSUE TITLE
False Positive when date is in UTC format

### ISSUE THREAD

**Issue by Blackjacx** [dblock/danger-changelog#59]
This tool generates a false positive when the date is in UTC format like in version 1.6.0 and 1.7.0 below. Version 1.4.2 does not trigger a warning. I use https://github.com/pajapro/fastlane-plugin-changelog with default parameters to generate the changelog. In version 0.16 they changed the timestamp to be UTC which adds the `Z` in the end. 

I'm not 100% sure if `2021-05-20Z` is a vaild ISO date since the Z is intended for the timezone and here is no time.

```
# Change Log

## [Unreleased]

## [1.7.0] - 2021-11-23Z
* [#37](https://github.com/Blackjacx/Columbus/pull/37): Replace images by emojis - [@Blackjacx](https://github.com/Blackjacx).

## [1.6.0] - 2021-05-20Z
* [#34](https://github.com/Blackjacx/Columbus/pull/34): XCFramework Compatibility - [@Blackjacx](https://github.com/Blackjacx).
* Simplify section index creation - [@Blackjacx](https://github.com/Blackjacx).
* Throw error instead of ignore missing flag icon - [@Blackjacx](https://github.com/Blackjacx).

## [1.4.2] - 2021-02-06
* Implement DisplayState - [@Blackjacx](https://github.com/Blackjacx).
* Inject config directly in ViewController - [@Blackjacx](https://github.com/Blackjacx).
```

**Comment by dblock** [comment]
I've never seen a date with a `Z`, but it makes a lot of sense since my today can be the same as your tomorrow. But I am getting philosophical :) 

You can try adding to https://raw.githubusercontent.com/dblock/danger-changelog/master/spec/intridea/fixtures/dates.md and it should visibly fail tests. I think this should be allowed.

**Comment by Blackjacx** [comment]
Yeah I also never saw that but for me it makes sense too for the reason you stated 👍🏼 I [created a PR](https://github.com/dblock/danger-changelog/pull/60) that adds the new date to the tests  but not sure what needs to be fixed to accept this kind of date...

**Comment by dblock** [comment]
Closing via https://github.com/dblock/danger-changelog/pull/61
